<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Site - Teste</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>

<body>
  <header class="bg-primary-subtle p-2">
    <ul class="nav nav-pills justify-content-end">
      <li class='nav-item'>
        <a class='nav-link fw-bold <?= ($this->getActive() == "index") ? 'active text-white': 'text-dark'?>' aria-current='page' href='/home'><i class='bi bi-book'></i> Livros</a>
      </li>
      <li class='nav-item'>
        <a class='nav-link fw-bold <?= ($this->getActive() == "carrinho") ? 'active text-white': 'text-dark'?>' href='/favoritos'><i class='bi bi-heart'></i> Favoritos</a>
      </li>
      <li class='nav-item'>
        <a class='nav-link fw-bold <?= ($this->getActive() == "favoritos") ? 'active text-white': 'text-dark'?>' href='/carrinho'><i class='bi bi-cart'></i> Carrinho</a>
      </li>
      <li class='nav-item'>
        <a class='nav-link fw-bold text-dark' href='/sair'><i class="bi bi-arrow-right-short"></i><i class="bi bi-door-open"></i> Sair</a>
      </li>
    </ul>
  </header>
  <main class="p-5">
    <?php
    $this->content();
    ?>
  </main>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>