<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
  <header class="p-5">
    <ul class="nav nav-tabs">
      <?php
        if($this->getActive() == "index"){
          echo "
          <li class='nav-item'>
            <a class='nav-link active' aria-current='page' href='/'>Home</a>
          </li>
          <li class='nav-item'>
            <a class='nav-link' href='/sobreNos'>Sobre Nos</a>
          </li>
          ";
        }
        else if($this->getActive() == "sobreNos"){
          echo "
          <li class='nav-item'>
            <a class='nav-link' aria-current='page' href='/'>Home</a>
          </li>
          <li class='nav-item'>
            <a class='nav-link active' href='/sobreNos'>Sobre Nos</a>
          </li>
          ";
        }
      ?>
      
    </ul>
  </header>
  <main class="p-5"> 
    <?php
      $this->content();
    ?>
  </main>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>
</html>