<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Site - Teste</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body class="w-100 vh-100 d-flex flex-wrap justify-content-center align-content-center bg-body-tertiary">
  <div class="modal-body p-5 pt-0 bg-white shadow rounded pt-5" style="max-width: 400px;">
    <form method="POST" action="/">
      <div class="form-floating mb-3">
        <input type="email" class="form-control rounded-3" name="email" placeholder="name@example.com" required>
        <label for="floatingInput">Email</label>
      </div>
      <div class="form-floating mb-3">
        <input type="password" class="form-control rounded-3" name="password" id="floatingPassword" placeholder="Password" required>
        <label for="floatingPassword">Senha</label>
      </div>
      <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Entrar</button>
      <?php if (isset($_SESSION['errorLogin'])) : ?>
        <div class="alert alert-danger text-center" role="alert">
          <?= $_SESSION['errorLogin']; ?>
        </div>
        <?php unset($_SESSION['errorLogin']);?>
      <?php endif; ?>
      <hr class="my-4">
      <small class="text-body-secondary">Faça login para poder aessar o sistema</small>
    </form>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
</body>

</html>